"""Aletheia wp-9: Brief Review Queue.

REST endpoints for the weekly-brief review flow. Briefs generated by
aletheia-brief (wp-8) land here in PENDING status; Helo reviews, edits,
and approves or rejects. Approved briefs persist to Pluteus under
``aletheia/briefs/<reader>/<YYYY-Www>/<slug>.md`` via the agent-write-api
using a dedicated aletheia token.

Endpoints
---------
POST   /api/briefs                        — land a new draft (from wp-8)
GET    /api/briefs/pending                — list briefs awaiting review
GET    /api/briefs/{id}                   — full brief detail
POST   /api/briefs/{id}/approve           — accept (optionally with edits)
POST   /api/briefs/{id}/reject            — reject with reason
GET    /api/briefs/{id}/diff              — per-sentence diff for wp-10
GET    /api/briefs/sent                   — archive of approved briefs

Approver guard
--------------
v1 only supports reader='rowen' and reader='helo'. Approving a brief
whose reader is 'rowen' requires the caller's username to match the
configured approver (default: 'helo'); briefs addressed to 'helo' may
be self-approved. Multi-reader scoping is v2.
"""

from __future__ import annotations

import json
import logging
import os
import re
import unicodedata
from datetime import datetime, timezone
from typing import Optional

import httpx
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import desc
from sqlalchemy.orm import Session

from app.auth import get_current_user
from app.database import get_db
from app.models import Brief, BriefEdit, BriefStatus, User
from app.schemas import (
    BriefApprove,
    BriefApproveResponse,
    BriefCreate,
    BriefDetail,
    BriefDiffResponse,
    BriefReject,
    BriefSummary,
    SentenceDiff,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/briefs", tags=["Briefs"])

# Who may approve a brief for a given reader. v1 hard-codes the mapping;
# v2 will read this from a config table. A reader who appears as their
# own approver (e.g. 'helo' -> 'helo') may self-approve.
_APPROVER_FOR_READER = {
    "rowen": os.environ.get("ALETHEIA_APPROVER_FOR_ROWEN", "helo"),
    "helo": "helo",
}

_PLUTEUS_URL = os.environ.get("ALETHEIA_PLUTEUS_URL", "http://localhost:8080").rstrip("/")
_PLUTEUS_TOKEN = os.environ.get("ALETHEIA_PLUTEUS_TOKEN")

# Sentence splitter mirrors the wp-8 post-splitter-fix behaviour:
# terminal punctuation may be followed by ``\s*[^N]`` runs that belong
# to the preceding sentence. UNSOURCED blocks are atomic.
_UNSOURCED_BLOCK_RE = re.compile(r"\[UNSOURCED:[^\]]*\]")
_CITATION_INLINE_RE = re.compile(r"\[\^([^\]]+)\]")
_FOOTNOTE_DEF_LINE_RE = re.compile(r"^\s*\[\^[^\]]+\]:")
_SENTENCE_BOUNDARY_RE = re.compile(
    r"(?<![0-9])[.!?]+(?:[\"')\]]+)?"
    r"(?:\s*\[\^[^\]]+\])*"
    r"(?=\s|$)"
)


# --------------------------------------------------------------------- helpers


def _to_detail(brief: Brief) -> BriefDetail:
    return BriefDetail(
        id=brief.id,
        reader=brief.reader,
        project=brief.project,
        date_range_start=brief.date_range_start,
        date_range_end=brief.date_range_end,
        markdown=brief.markdown,
        citations=json.loads(brief.citations_json or "{}"),
        ungrounded_flags=json.loads(brief.ungrounded_flags_json or "[]"),
        grounded_pct=float(brief.grounded_pct or 0.0),
        hallucination_risk=float(brief.hallucination_risk or 0.0),
        status=brief.status,
        edited_markdown=brief.edited_markdown,
        reject_reason=brief.reject_reason,
        pluteus_slug=brief.pluteus_slug,
        pluteus_sync_error=brief.pluteus_sync_error,
        generated_at=brief.generated_at,
        reviewed_at=brief.reviewed_at,
    )


def _to_summary(brief: Brief) -> BriefSummary:
    flags = json.loads(brief.ungrounded_flags_json or "[]")
    return BriefSummary(
        id=brief.id,
        reader=brief.reader,
        project=brief.project,
        date_range_start=brief.date_range_start,
        date_range_end=brief.date_range_end,
        generated_at=brief.generated_at,
        grounded_pct=float(brief.grounded_pct or 0.0),
        hallucination_risk=float(brief.hallucination_risk or 0.0),
        ungrounded_count=len(flags),
        status=brief.status,
    )


def _may_approve(reader: str, username: str) -> bool:
    required = _APPROVER_FOR_READER.get(reader)
    if not required:
        return False
    return username.lower() == required.lower()


def _split_sentences(line: str) -> list[str]:
    """Mask-aware splitter matching the wp-8 generator's behaviour."""
    blocks: list[str] = []

    def _mask(match: re.Match) -> str:
        idx = len(blocks)
        blocks.append(match.group(0))
        return f"\u0001UNSRC{idx}\u0001"

    masked = _UNSOURCED_BLOCK_RE.sub(_mask, line)
    pieces: list[str] = []
    cursor = 0
    for match in _SENTENCE_BOUNDARY_RE.finditer(masked):
        end = match.end()
        chunk = masked[cursor:end].strip()
        if chunk:
            pieces.append(chunk)
        cursor = end
    tail = masked[cursor:].strip()
    if tail:
        pieces.append(tail)

    def _unmask(piece: str) -> str:
        for idx, original in enumerate(blocks):
            piece = piece.replace(f"\u0001UNSRC{idx}\u0001", original)
        return piece

    return [_unmask(p) for p in pieces]


def _iter_prose_sentences(markdown: str) -> list[str]:
    """Iterate every prose sentence in the brief.

    Skips fenced code, blank lines, and footnote-definition lines in the
    Citations section so edits to footnote text don't count as content
    changes worth backpropping.
    """
    sentences: list[str] = []
    in_fence = False
    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or not line:
            continue
        if _FOOTNOTE_DEF_LINE_RE.match(line):
            continue
        # Strip leading bullet + heading markers before splitting.
        stripped = re.sub(r"^(?:\s*[-*]\s+|#+\s+)", "", line)
        sentences.extend(_split_sentences(stripped))
    return sentences


def _citation_ids_for(sentence: str) -> list[str]:
    return [m.group(1) for m in _CITATION_INLINE_RE.finditer(sentence)]


def _levenshtein(a: str, b: str) -> int:
    """Small, stdlib-only Levenshtein for edit-distance scoring."""
    if a == b:
        return 0
    if not a:
        return len(b)
    if not b:
        return len(a)
    if len(a) < len(b):
        a, b = b, a
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        curr = [i]
        for j, cb in enumerate(b, 1):
            ins = curr[j - 1] + 1
            dele = prev[j] + 1
            sub = prev[j - 1] + (ca != cb)
            curr.append(min(ins, dele, sub))
        prev = curr
    return prev[-1]


def _normalise(text: str) -> str:
    """NFC + collapse runs of whitespace — matches ignore trivial edits."""
    return re.sub(r"\s+", " ", unicodedata.normalize("NFC", text)).strip()


def _compute_sentence_diffs(original_md: str, edited_md: str) -> list[SentenceDiff]:
    """Pair-wise per-sentence diff, best-effort alignment.

    v1 is position-based: if both briefs split to the same sentence
    count, pair them index-for-index and emit a diff for every pair
    whose normalised text differs. If the counts differ (Helo added or
    removed sentences), we fall back to emitting a single whole-brief
    synthetic diff — the edit_distance is then the full Levenshtein
    across the prose, and sources_cited is the union of every cited id
    in either version. Good enough for wp-9; wp-10 can refine.
    """
    o = _iter_prose_sentences(original_md)
    e = _iter_prose_sentences(edited_md)
    if len(o) == len(e):
        diffs: list[SentenceDiff] = []
        for orig, edt in zip(o, e):
            if _normalise(orig) == _normalise(edt):
                continue
            diffs.append(SentenceDiff(
                original=orig,
                edited=edt,
                sources_cited=_citation_ids_for(orig),
                distance=_levenshtein(_normalise(orig), _normalise(edt)),
            ))
        return diffs
    # Sentence-count mismatch — fall back.
    logger.info(
        "brief diff sentence count mismatch: original=%d edited=%d; "
        "using whole-brief fallback",
        len(o), len(e),
    )
    ids: set[str] = set()
    for s in o + e:
        ids.update(_citation_ids_for(s))
    return [SentenceDiff(
        original="\n".join(o),
        edited="\n".join(e),
        sources_cited=sorted(ids),
        distance=_levenshtein(_normalise("\n".join(o)), _normalise("\n".join(e))),
    )]


def _write_to_pluteus(brief: Brief, markdown: str) -> tuple[Optional[str], Optional[str]]:
    """POST an approved brief to Pluteus. Returns (slug, error).

    Degrades to (None, "<reason>") when Pluteus isn't reachable or the
    aletheia token isn't configured — we still approve the brief, but
    surface the sync issue in ``pluteus_sync_error`` for Helo to notice.
    """
    if not _PLUTEUS_TOKEN:
        return None, "ALETHEIA_PLUTEUS_TOKEN not configured"
    iso_week = brief.date_range_end.strftime("%Y-W%U")
    slug_base = f"aletheia-{brief.reader}-{iso_week}-{brief.project.lower()}"
    try:
        resp = httpx.post(
            f"{_PLUTEUS_URL}/api/v1/docs",
            headers={"Authorization": f"Bearer {_PLUTEUS_TOKEN}"},
            json={
                "title": f"Weekly brief — {brief.project} — {iso_week}",
                "body": markdown,
                "tags": ["aletheia", "brief", brief.reader, brief.project],
            },
            timeout=10.0,
        )
        if resp.status_code >= 300:
            return None, f"pluteus returned {resp.status_code}: {resp.text[:200]}"
        payload = resp.json()
        return payload.get("slug", slug_base), None
    except (httpx.RequestError, ValueError) as exc:
        return None, f"pluteus request failed: {exc}"


# --------------------------------------------------------------------- routes


@router.post("", response_model=BriefDetail, status_code=status.HTTP_201_CREATED)
def create_brief(
    payload: BriefCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> BriefDetail:
    """Land a draft from aletheia-brief. Status starts PENDING."""
    brief = Brief(
        reader=payload.reader,
        project=payload.project,
        date_range_start=payload.date_range_start,
        date_range_end=payload.date_range_end,
        markdown=payload.markdown,
        citations_json=json.dumps(payload.citations),
        ungrounded_flags_json=json.dumps(payload.ungrounded_flags),
        grounded_pct=f"{payload.grounded_pct}",
        hallucination_risk=f"{payload.hallucination_risk}",
        status=BriefStatus.PENDING,
    )
    db.add(brief)
    db.commit()
    db.refresh(brief)
    logger.info(
        "brief created id=%d reader=%s project=%s grounded_pct=%.3f",
        brief.id, brief.reader, brief.project, payload.grounded_pct,
    )
    return _to_detail(brief)


@router.get("/pending", response_model=list[BriefSummary])
def list_pending(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[BriefSummary]:
    """Briefs awaiting review, newest-first."""
    briefs = (
        db.query(Brief)
        .filter(Brief.status == BriefStatus.PENDING)
        .order_by(desc(Brief.generated_at))
        .all()
    )
    return [_to_summary(b) for b in briefs]


@router.get("/sent", response_model=list[BriefSummary])
def list_sent(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[BriefSummary]:
    """Archive of approved briefs, newest-first."""
    briefs = (
        db.query(Brief)
        .filter(Brief.status == BriefStatus.APPROVED)
        .order_by(desc(Brief.reviewed_at))
        .all()
    )
    return [_to_summary(b) for b in briefs]


@router.get("/{brief_id}", response_model=BriefDetail)
def get_brief(
    brief_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> BriefDetail:
    brief = db.query(Brief).filter(Brief.id == brief_id).first()
    if not brief:
        raise HTTPException(status_code=404, detail="Brief not found")
    return _to_detail(brief)


@router.get("/{brief_id}/diff", response_model=BriefDiffResponse)
def diff_edits(
    brief_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> BriefDiffResponse:
    """Diff an approved brief's edits against its original for wp-10."""
    brief = db.query(Brief).filter(Brief.id == brief_id).first()
    if not brief:
        raise HTTPException(status_code=404, detail="Brief not found")
    if not brief.edited_markdown or brief.edited_markdown == brief.markdown:
        return BriefDiffResponse(brief_id=brief_id, sentence_diffs=[], total_edit_distance=0)
    diffs = _compute_sentence_diffs(brief.markdown, brief.edited_markdown)
    total = sum(d.distance for d in diffs)
    return BriefDiffResponse(brief_id=brief_id, sentence_diffs=diffs, total_edit_distance=total)


@router.post("/{brief_id}/approve", response_model=BriefApproveResponse)
def approve_brief(
    brief_id: int,
    payload: BriefApprove,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> BriefApproveResponse:
    """Accept a brief, optionally with edits. Persist to Pluteus."""
    brief = db.query(Brief).filter(Brief.id == brief_id).first()
    if not brief:
        raise HTTPException(status_code=404, detail="Brief not found")
    if brief.status != BriefStatus.PENDING:
        raise HTTPException(
            status_code=409,
            detail=f"Brief already {brief.status.value}; cannot approve",
        )
    if not _may_approve(brief.reader, current_user.username):
        raise HTTPException(
            status_code=403,
            detail=(
                f"User {current_user.username!r} is not the approver for "
                f"reader={brief.reader!r}"
            ),
        )

    final_markdown = payload.edited_markdown if payload.edited_markdown else brief.markdown
    diffs: list[SentenceDiff] = []
    total_distance = 0
    sources_backpropped = 0

    if payload.edited_markdown and payload.edited_markdown != brief.markdown:
        diffs = _compute_sentence_diffs(brief.markdown, payload.edited_markdown)
        total_distance = sum(d.distance for d in diffs)
        for d in diffs:
            edit = BriefEdit(
                brief_id=brief.id,
                sentence_original=d.original,
                sentence_edited=d.edited,
                sources_cited_json=json.dumps(d.sources_cited),
                edit_distance=d.distance,
            )
            db.add(edit)
            sources_backpropped += len(d.sources_cited)
        brief.edited_markdown = payload.edited_markdown

    slug, sync_error = _write_to_pluteus(brief, final_markdown)
    brief.pluteus_slug = slug
    brief.pluteus_sync_error = sync_error
    brief.status = BriefStatus.APPROVED
    brief.reviewed_at = datetime.now(timezone.utc)
    brief.approver_id = current_user.id

    db.commit()
    db.refresh(brief)

    return BriefApproveResponse(
        id=brief.id,
        status=brief.status,
        pluteus_slug=brief.pluteus_slug,
        pluteus_sync_error=brief.pluteus_sync_error,
        edit_distance=total_distance,
        sources_backpropped=sources_backpropped,
    )


@router.post("/{brief_id}/reject", response_model=BriefDetail)
def reject_brief(
    brief_id: int,
    payload: BriefReject,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> BriefDetail:
    """Reject a brief with reason. Does not retry — next cycle generates fresh."""
    brief = db.query(Brief).filter(Brief.id == brief_id).first()
    if not brief:
        raise HTTPException(status_code=404, detail="Brief not found")
    if brief.status != BriefStatus.PENDING:
        raise HTTPException(
            status_code=409,
            detail=f"Brief already {brief.status.value}; cannot reject",
        )
    if not _may_approve(brief.reader, current_user.username):
        raise HTTPException(
            status_code=403,
            detail=(
                f"User {current_user.username!r} is not the approver for "
                f"reader={brief.reader!r}"
            ),
        )

    brief.reject_reason = payload.reason
    brief.status = BriefStatus.REJECTED
    brief.reviewed_at = datetime.now(timezone.utc)
    brief.approver_id = current_user.id
    db.commit()
    db.refresh(brief)
    return _to_detail(brief)
